export const THEMES = {
    ORIGINAL: {
      name: 'Full',
      background: 'from-purple-400 via-pink-500 to-red-500',
      cardBg: 'bg-[#E04025]',
      cardHoverBg: 'hover:bg-[#E04025]/90',
      overlayBg: 'bg-white/10',
      emoji: '🍀',
      textColor: 'text-black',
      frameFill: '#F9D025',
      isDark: false,
    },
    WICKED: {
      name: 'Wicked',
      background: 'from-purple-400 via-pink-500 to-red-500',
      cardBg: 'bg-[#F5818B]',
      cardHoverBg: 'hover:bg-[#F5818B]/90',
      overlayBg: 'bg-white/10',
      emoji: '🍀',
      textColor: 'text-black',
      frameFill: '#3EA345',
      isDark: false,
    },
    SKYBLUE: {  
      name: 'Ocean',
      background: 'from-emerald-800 via-green-600 to-lime-500',
      cardBg: 'bg-[#B3D9F6]',
      cardHoverBg: 'hover:bg-[#B3D9F6]/90',
      overlayBg: 'bg-emerald-100/20',
      emoji: '🦋',
      textColor: 'text-black',
      frameFill: '#326FC9',
      isDark: false,
    },
    DARK: {
      name: 'Night',
      background: 'from-slate-950 to-slate-900',
      cardBg: 'bg-[#D9D9D9]',
      cardHoverBg: 'hover:bg-[#D9D9D9]/90',
      overlayBg: 'bg-slate-800/30',
      emoji: '🌚',
      textColor: 'text-white', 
      frameFill: '#000000',
      isDark: true,
    },
    SUNSET: {
      name: 'Huat',
      background: 'bg-white',
      cardBg: 'bg-[#F9D025]',
      cardHoverBg: 'hover:bg-[#F9D025]/90',
      overlayBg: 'bg-orange-100/20',
      emoji: '🌅',
      borderClass: 'border-black border',
      textColor: 'text-black',
      frameFill: '#E04025',
      isDark: false,
    },
  };